### ISSUE TITLE
Missing code for few-shot experiment

### ISSUE THREAD

**Issue by V0XNIHILI** [smonsays/contrastive-meta-learning#1]
Title mentions it already, but are you planning to upload code for the few shot experiment soon?

**Comment by Johswald** [comment]
Hey! Thanks for your interest. I will upload the code this, latest next week. Best, Johannes

**Comment by Johswald** [comment]
Hey! Sorry for the delay - just uploaded the code. Hope you can easily run the code. Let us know if there are any more issues.

**Comment by V0XNIHILI** [comment]
Thanks a lot!
